### ISSUE TITLE
Custom installation path removed.

### ISSUE THREAD

**Issue by LordEmer** [codewithmei/wuwa.mei-labs.com#1]
Hi, great website. It worked really well, and I see you are expanding it well.
However it stopped working for me since I have custom installation path, and you removed that from options to enter :)
![image](https://github.com/codewithmei/wuwa.mei-labs.com/assets/64984365/cccb2257-ec90-4247-acaf-8cc14a5bf446)

The powershell gives me exception since its not in default path.
![image](https://github.com/codewithmei/wuwa.mei-labs.com/assets/64984365/7b8fe370-ace3-4731-bb1e-a1830637a16a)
****

Convene records was open all the time.
![image](https://github.com/codewithmei/wuwa.mei-labs.com/assets/64984365/362544a9-0a08-4b7a-9be2-bc46912a322f)

Good luck with project! Thanks for making it.

**Comment by codewithmei** [comment]
Hi @LordEmer  yes, I removed the custom installation path from the website and moved it into PowerShell. Based on your screenshot, PowerShell asks you to enter the correct game installation path, but you didn't enter the correct path (you pasted the script that you copied from the website).

**Comment by LordEmer** [comment]
oh I see, so it was powershell command with input. Sry I was used to the one line that just got me a url code
