### ISSUE TITLE
First one in limited banner is not Guaranteed

### ISSUE THREAD

**Issue by LordEmer** [codewithmei/wuwa.mei-labs.com#2]
Hey another small issue if you weren't aware of it yet.
Only limited banner have guarantee and first 5 star pull in limited banner is not "Guaranteed"

If first 5* from limited banner is limited banner 5* character/weapon we call it "Win" in 50/50
Next 5* then is another 50/50 coin flip for Win/Lose

If first 5* from limited banner is standard 5* character/weapon we call it "Lose" in 50/50
Then if you Lost it once the next one is Guaranteed to be limited 5* and that 2nd drop from "Lose" is called "Guaranteed"
After those two its reset and the next 5* is a coin flip for Win/Lose

We always start with No Guarantee

From programming view:

Guarantee = false //No Guarantee at first

5* drops, it goes into this function:

```
If (!Guarantee)
{
   if (5*drop == limited)
      Return Win
   else
      Guarantee = true
      Return Lose
}
Else
   Guarantee = false
   Return Guaranteed
```

![image](https://github.com/codewithmei/wuwa.mei-labs.com/assets/64984365/6e55b87b-a61a-4353-8c17-161fa1384034)
In this image, its my first 5* from all limited pulls and I got a limited Character so it should be Win instead of Guaranteed.
Guaranteed is only if I were to Lose first (so get a Standard 5* before) then get a Limited 5* after.

Sorry, for long winded explanation. If you knew this before this probably bored you to death, but I tried to explain it as clearly as possible as so anyone would get it.
Thanks for making the tracker.

P.S. If possible can we get a Pity Distribution please?
A lot of us are interested in that. Data at which pity 5* drops (in my SS its 60 for mine). We are interested at which number the % is highest.
If you need help with some programming I can do it, but I never tried to do GitHub before so no idea where to start haha.

**Comment by LordEmer** [comment]
Afterthoughts:
I don't know how data is presented to you, but if its not stated directly which character/weapon is limited then it might be better to check for standard first since that is almost permanent.

```
If (!Guarantee)
{
  if (isStandard(5*drop))  //in that case probably will need to write separate function to check
    Guarantee = true
    Return Lose
  else
    Return Win
}
Else
  //If it's Guaranteed then the 5* is bound to be limited so no need to check. We remove Guarantee and go on.
  Guarantee = false
  Return Guaranteed
```

**Comment by codewithmei** [comment]
Hi, I've resolved the issue regarding incorrect 'win' data. Could you please check your table to ensure that the 'win' status for Yinlin is correct?

Additionally, try reimporting your convene record to see if this resolves the issue.

**Comment by codewithmei** [comment]
I also added a pity stats for 4 star and 5 star:

![wuthering xyz_convene_global (1)](https://github.com/codewithmei/wuwa.mei-labs.com/assets/128881536/d4693089-e545-4dde-bf22-063a4a92fb19)

![wuthering xyz_convene_global (2)](https://github.com/codewithmei/wuwa.mei-labs.com/assets/128881536/a3f8fd92-667f-4344-8eba-a702b428247e)

**Comment by LordEmer** [comment]
Wow, it's great!!!
Thank you very much for pity stats, that was lightning fast.
