### ISSUE TITLE
Unable to register - Google says "Registration of a new user is not allowed."

### ISSUE THREAD

**Issue by LostLogic** [codewithmei/wuwa.mei-labs.com#4]
![image](https://github.com/codewithmei/wuwa.mei-labs.com/assets/7568950/9a60fc51-1795-4566-b52d-89df1faf0d81)

Currently impossible to register to add convenes to the site. As far as I can tell, only Google registrations are allowed.

**Comment by codewithmei** [comment]
> ![image](https://github.com/codewithmei/wuwa.mei-labs.com/assets/7568950/9a60fc51-1795-4566-b52d-89df1faf0d81)
> 
> Currently impossible to register to add convenes to the site. As far as I can tell, only Google registrations are allowed.

~~Could you try using this link to log in with Google:~~

~~https://wuthering.xyz/convene/oauth/google~~

**Comment by codewithmei** [comment]
Hi, @LostLogic , I fixed the issue with google login. Try pressing the "Sign in with Google" button at [https://wuthering.xyz/convene/import](https://wuthering.xyz/convene/import)

**Comment by LostLogic** [comment]
Excellent! I can confirm it's working properly now. Thank you!
